Add growth rate <-> doubling time functions
rethinkpriorities/squigglepy pull request #10
Opened 2023-03-16 23:09 UTC by erwald

This closes #8.

I wasn't sure how to best fit it into the existing file structure, so definitely feel free to request changes.

Also, I chose to represent growth rates as fractions where e.g. 0.05 == +5%, but maybe it's more natural to let 1.05 == +5%? I could see it either way, anyway it's easy enough to change.

2023-03-17 01:38 UTC, peterhurford requested changes

2023-03-17 01:38 UTC, peterhurford commented on squigglepy/utils.py
> +    if is_dist(growth_rate):
Great use of `is_dist` :)

2023-03-17 01:38 UTC, peterhurford commented on squigglepy/utils.py
> +    elif isinstance(growth_rate, np.ndarray):
Unsure but you could consider use `_is_numpy` from utils if you want to capture numpy things other than numpy arrays

2023-03-17 01:38 UTC, peterhurford commented on squigglepy/utils.py
> +        return (math.log(2) / doubling_time).exp() - 1
Similar to above would rather have a squigglepy-speicfic `exp` or `dist_exp` function

2023-03-17 01:38 UTC, peterhurford commented on tests/test_utils.py
> +    assert doubling_time_to_growth_rate(const(12)) @ 1 == 0.05946309435929531
Tests look great - thanks!

2023-03-17 01:38 UTC, peterhurford commented on CHANGES.md
> +* Added `growth_rate_to_doubling_time` and `doubling_time_to_growth_rate` convenience functions. These take numbers, numpy arrays or distributions.
Good use of `CHANGES.md`!

2023-03-18 14:03 UTC, erwald commented
@peterhurford Thanks, I've pushed some changes, lmk how it looks!

2023-03-19 04:17 UTC, peterhurford approved these changes

2023-03-19 04:17 UTC, merged

2023-03-19 04:18 UTC, peterhurford commented
Thanks!